### PR TITLE
add sync labels

### PR DESCRIPTION
**Pull request by cpanato**
- add sync labels to the org

### CODE REVIEW

**Review by patflynn — APPROVED** [review]
Thanks Carlos!  This is probably a dumb idea, but could we skip the labels.json and just use the labels on this ,github repo to be the authoratative source?

**Comment by cpanato** [comment]
> Thanks Carlos! This is probably a dumb idea, but could we skip the labels.json and just use the labels on this ,github repo to be the authoratative source?


i think we can, but then we will not have the audit part in case we need it (who knows 🤷‍♂️ ) and will make hard to know who change what/when

but i can implement that in a follow up if you would like/want

**Comment by patflynn** [comment]
Nah this is good. Thanks again!

**Comment by cpanato** [comment]
will merge to test this

**Comment by patflynn** [comment]
works towards #933

**Pull request merged**
